e = str(input('Digite alguma coisa:'))
print(type(e))
print('É alfabético?', e.isalpha())
print('É Numérico?', e.isnumeric())
print('É alfanumérico?', e.isalnum())
print('é alguma coisa?', e.isascii())
print('é algo?', e.isalpha())
print('é alguma coisa que não sei mexer ainda então vamos ganhar tempo', e.isprintable())
print('vamos testando, apenas para faze ro video!!', e.isprintable())
print('vamos ver o resultado de como ficou o video?', e.isupper())
print('Acreido que o video tenha ficado muito bom, e este teclado que estou usando é muito confortavel!')
