n = int(input('Digite um número: '))
x1 = (n*1)
x2 = (n*2)
x3 = (n*3)
x4 = (n*4)
x5 = (n*5)
x6 = (n*6)
x7 = (n*7)
x8 = (n*8)
x9 = (n*9)
x10 = (n*10)
print ('A tabuada do número digitado é:')
print (n,'X 1 = {}'.format(x1))
print (n,'X 2 = {}'.format(x2))
print (n,'X 3 = {}'.format(x3))
print (n,'X 4 = {}'.format(x4))
print (n,'X 5 = {}'.format(x5))
print (n,'X 6 = {}'.format(x6))
print (n,'X 7 = {}'.format(x7))
print (n,'X 8 = {}'.format(x8))
print (n,'X 9 = {}'.format(x9))
print (n,'X 10 = {}'.format(x10))

